name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        npm install
        npm install playwright

    - name: Install JDK
      run: |
        brew install openjdk@11
        echo 'export PATH="/usr/local/opt/openjdk@11/bin:$PATH"' >> $HOME/.zshrc  # Update this line based on your shell (e.g., .bashrc for Bash)

    - name: Install Chrome
      run: |
        brew install --cask google-chrome

    - name: Build
      run: npm run build

    - name: Run Tests
      run: npm test

  deploy:
    runs-on: macos-latest
    needs: build
    steps:
    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
