name: CI/CD Pipeline

on:
  push:
    branches:
      - OrangeHRM_Framework

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        npm install
        npm install playwright

    - name: Install JDK
      run: |
        brew install openjdk@11
        echo 'export PATH="/usr/local/opt/openjdk@11/bin:$PATH"' >> $HOME/.zshrc  # Update this line based on your shell (e.g., .bashrc for Bash)

    - name: Install Chrome
      run: |
        brew install --cask google-chrome

    - name: Build
      run: npm run build

    - name: Run Tests
      run: |
        java -cp /home/vimmy/.m2/repository/org/testng/testng/7.9.0/testng-7.9.0.jar:/Users/vimmy/Documents/GitHub/OrangeHRMFramework/src/test/java/com/qa/orangeHRM/test:/Users/vimmy/Documents/GitHub/OrangeHRMFramework/src/test/resources/TestRunners/Regression.xml
        # Replace the placeholders with the actual paths to your TestNG jar file, test-classes, and testng.xml

  deploy:
    runs-on: macos-latest
    needs: build
    steps:
    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
